# Generated by Django 5.1.1 on 2024-11-29 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonRelatedName', models.CharField(max_length=63)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='CompanyUndertakingWork',
        ),
        migrations.AddField(
            model_name='project',
            name='ProjectPersonRelated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_person_related', to='api.personrelated'),
        ),
    ]
