# Generated by Django 5.1.4 on 2024-12-07 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_project_projectpersonrelated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50)),
                ('Amount', models.FloatField(blank=True, null=True)),
                ('AppointmentType', models.CharField(blank=True, max_length=50, null=True)),
                ('Site', models.CharField(blank=True, max_length=255, null=True)),
                ('RelatedPerson', models.CharField(blank=True, max_length=255, null=True)),
                ('Note', models.TextField(blank=True, null=True)),
                ('Date', models.DateTimeField()),
                ('Calendar_Client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_calendar', to='api.clients')),
                ('Calendar_PowerPlant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='powerplant_calendar', to='api.powerplant')),
                ('Calendar_Supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_calendar', to='api.supplier')),
            ],
        ),
    ]
